### ISSUE TITLE
Problems in installation of MSNoise_tomo

### ISSUE THREAD

**Issue by Akashkharita** [ThomasLecocq/msnoise-tomo#25]
Hi Thomas,

I am trying to install msnoise_tomo, to begin with - 
whenever I type 
python setup.py install in the main directory, I get following error - 
![image](https://user-images.githubusercontent.com/51695294/121805815-7535ec80-cc6a-11eb-861e-a31d04190147.png)

**Comment by Akashkharita** [comment]
same problem when i use 'python setup.py build'
![image](https://user-images.githubusercontent.com/51695294/121806045-bc70ad00-cc6b-11eb-8aa9-712701af99c3.png)

**Comment by ThomasLecocq** [comment]
Please add 

- the output of "conda list"
- the content of the PATH environment variable

And please check that non existing path exists

**Comment by Akashkharita** [comment]
Hi Thomas,

The path was not existing. 
Then I reinstalled the visual c++ library with dependencies mentioned here (second answer)  - https://stackoverflow.com/questions/48541801/microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-t

Then when i ran        python setup.py install 
It appears to work fine. 

![image](https://user-images.githubusercontent.com/51695294/121836094-6e51bd00-ccf0-11eb-84d0-b22212a3fc03.png)
![image](https://user-images.githubusercontent.com/51695294/121836109-76116180-ccf0-11eb-9fcf-f2f83d59c8f6.png)
with the final message being this - 
![image](https://user-images.githubusercontent.com/51695294/121836178-9fca8880-ccf0-11eb-85e6-a1d1fc46891f.png)

Then I ran python setup.py build
![image](https://user-images.githubusercontent.com/51695294/121836353-e324f700-ccf0-11eb-91fd-efab8976a0e3.png)

But when i ran msnoise -p tomo info 
it displays this error
(base) C:\Users\akash\msnoise__testing\msnoise-tomo-master>msnoise p tomo info
![image](https://user-images.githubusercontent.com/51695294/121836442-0a7bc400-ccf1-11eb-8c53-68b8aa06cfb1.png)

and here is my conda list 
![image](https://user-images.githubusercontent.com/51695294/121836549-4b73d880-ccf1-11eb-98f7-23e53eb3a213.png)
![image](https://user-images.githubusercontent.com/51695294/121836572-56c70400-ccf1-11eb-97f7-466dfaf8c9ec.png)
![image](https://user-images.githubusercontent.com/51695294/121836589-60506c00-ccf1-11eb-9626-d7e03b337bf1.png)
![image](https://user-images.githubusercontent.com/51695294/121836608-6c3c2e00-ccf1-11eb-9f7c-df6a23a0f894.png)
![image](https://user-images.githubusercontent.com/51695294/121836619-73fbd280-ccf1-11eb-8b61-d2b21c6f3ac6.png)
![image](https://user-images.githubusercontent.com/51695294/121836641-82e28500-ccf1-11eb-85b8-ac04074a8851.png)
![image](https://user-images.githubusercontent.com/51695294/121836666-8f66dd80-ccf1-11eb-97d5-8e6ed665c180.png)

**Comment by Akashkharita** [comment]
Hi Thomas!

It worked! I just had to set the plugin, define the station coordinates and move to directory where db.ini was present.

Thanks a lot for your help.

**Comment by ThomasLecocq** [comment]
Hey, for future users, please :

list the different steps you had to do to build on windows

note: "conda list > list.txt" outputs the list to a file, easier to read/parse than your screenshots :-)

Thomas

**Comment by Akashkharita** [comment]
Sounds good! This was my first time opening an issue on github. 
Just to close it off. here are the steps  - 
My os was Windows10 
1) Install the Visual C++ library from with specific dependencies mentioned in the second answer here - https://stackoverflow.com/questions/48541801/microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-t
2) Go to the directory where db.ini is present.
3) Setup the station coordinates and height.
4) Follow the steps from starting given here - http://msnoise.org/plugins/msnoise-tomo/doc/

here is a file containing the output of conda list - 
[list.txt](https://github.com/ThomasLecocq/msnoise-tomo/files/6647794/list.txt)

Regards
Akash
