### ISSUE TITLE
Trying to understand TOMO_DISP data

### ISSUE THREAD

**Issue by dylanmikesell** [ThomasLecocq/msnoise-tomo#7]
I am working on trying to get through the whole tomography process with this code, but having some slight confusion and not sure how to fix because documentation doesn't explain.

When I run `msnoise p tomo ftan -s 0` it runs through all of my data and returns the following files.

GP.01101_GP.01102_MEAN.sac_FP.txt
GP.01101_GP.01102_MEAN.sac_TV.txt
GP.01101_GP.01102_MEAN.sac_amp.txt
GP.01101_GP.01102_MEAN.sac_disp.txt
GP.01101_GP.01102_MEAN.sac_ph.txt

These files are created for each station pair; the example above is for stations 01101 and 01102 in the GP network. I ask for the following periods

   0.0333
    0.0345
    0.0357
    0.0370
    0.0385
    0.0400
    0.0417
    0.0435
    0.0455
    0.0476
    0.0500
    0.0526
    0.0556
    0.0588
    0.0625
    0.0667
    0.0714
    0.0769
    0.0833
    0.0909
    0.1000
    0.1111
    0.1250
    0.1429
    0.1667
    0.2000

using the `ftan_periods` field in the tomo config. These are frequencies 5-30 Hz, spaced every 1 Hz. I have also set `ftan_nfreq`=41, which as I understand it means that the FTAN matrix will have 41 columns spanning `ftan_fmin`=5 to `ftan_famx=30` in my particular case.

One station output then looks like

```
fmin=5, fmax=30, nfreqs=41
bmin=0.02, bmax=2
ampMin=0.05
vgMin=0.07 vgMax=0.4
disp: no
diag: Period - Vgroup
out: enable (matrix)
max: 5.22906
write amplitude
write phase
write FT
write TV
fmin=5, fmax=30, nfreqs=41
bmin=0.02, bmax=2
ampMin=0.05
vgMin=0.07 vgMax=0.4
disp: cont,  finit=5.22906 tginit=4.67366e-310
diag: Period - Vgroup
out: enable (matrix)
max: 5.22906
freq near 5.22906 = 5.22906
write amplitude
write phase
write FT
write TV
[ 0.033  0.034  0.036  0.037  0.038  0.04   0.042  0.043  0.045  0.048
  0.05   0.053  0.056  0.059  0.062  0.067  0.071  0.077  0.083  0.091
  0.1    0.111  0.125  0.143  0.167  0.2  ]
[        nan  0.08543644         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan]
```

That makes sense. I understand that nans. That can be because of how close the stations are or the minimum amplitude parameter, `ftan_ampmin`=0.05.

What I do not understand is the resulting TOMO_DISP/ files. For example, for the stations above, I get the file TOMO_DISP/01/ZZ/GP_01101_GP_01102_MEAN.csv, which contains

,GP.01101_GP.01102_MEAN.sac
0.0,
0.1,0.192776595044
0.2,
0.30000000000000004,
0.4,
0.5,
0.6000000000000001,
0.7000000000000001,
0.8,
0.9,
1.0,
1.1,
1.2000000000000002,
1.3,
1.4000000000000001,
1.5,
1.6,
1.7000000000000002,
1.8,
1.9000000000000001,
2.0,

Now, I would have thought this contains two columns, Period and Velocity. But it does not appear to be the case. Can someone please explain this file to me? And I thought that running`msnoise p tomo prepare_tomo` combines the information in the TOMO_DISP folder into tomography input files on a per period basis in TOMO_FILES, but I don't think that can be because of the information contained in the DISP file above and the information we see in the TOMO_FILE below.

We had other issues (issue #4) with the small values of the periods (i.e. < 1.0). I wonder if there is another issues here. For example, let's look at the top three lines of the file for 0.2s period.

`$ more TOMO_FILES/01/ZZ/TestGroupVel_0.2sGLISN.dat `

GP.01101 GP.01102 0.2 0.192776595044 0 15.9273541759
GP.01101 GP.01103 0.2 0.26905235881 0 35.7949056343
GP.01101 GP.01104 0.2 0.108233877741 0 55.4774217922

We can see that stations GP.01101-GP.01102 at 0.2 s have a velocity of 0.192776595044 km/s,  0 is for the std. deviation and 15.9273541759 is the distance between stations. 

Where did this information come from if not the TOMO_DISP/ files? And what is the point of the TOMO_DISP files? I confused as to the linearity of steps in the process. The DISP file above shows a velocity of this amount but for 0.1 s period (if I can interpret the first column as the period).

I am happy to dig through the source code to figure this out, but was hoping Tom or Aurelien can give a quicker answer. Thanks! (And we should add some documentation once this is figured out...which I can help with.)

**Comment by Sion7291** [comment]
Hi,
Can anyone explain how one should select values of bmin and bmax??

**Comment by ThomasLecocq** [comment]
@Sion7291 please open another issue for questions, or better, ask on the MSNoise mailing list.

```
The bmin and bmax parameters are the bandwidth min and max of the gaussian
filters used in the FTAN algorithm.

The FTAN applies a set a gaussian filters to the seismograms with different
central frequencies. The width of the filter (in Hz) for the minimum
central frequency is bmin and vice versa for bmax. The width for the
intermediate filters increases linearly between bmin and bmax.

These parameters are equivalent to the "alpha" parameters in this paper
defining the FTAN:

Herrmann, R. B. (1973). Some aspects of band-pass filtering of surface
waves. *Bulletin of the Seismological Society of America*, *63*(2), 663-671.
```
